config/routes.rb
require 'resque/server'

Radar::Application.routes.draw do  
  mount Resque::Server, :at => '/resque'

  match '/auth/:provider/callback' => 'sources#create'
  match '/auth/failure' => 'sources#index'

  match '/sign_up' => 'users#new', as: :sign_up
  match '/sign_in' => 'user_sessions#new', as: :sign_in
  match '/logout' => 'user_sessions#destroy', as: :logout
  match '/account' => 'users#edit', as: :account
  match '/dashboard' => 'dashboards#show', as: :dashboard
  match '/linked_accounts' => 'sources#index', as: :linked_accounts

  resources :users, only: [:new, :create, :edit, :update]
  resource :user_session, only: [:new, :create, :destroy]
  resource :dashboard, only: [:show]
  resources :sources, only: [:index, :destroy]
  resources :contacts, only: [:show]
  resources :search, only: [:index]

  resources :phone_data, only: [] do
    collection do
      post :synchronize, defaults: { format: :json }
    end
  end
  resources :email_accounts, only: [] do
    collection do
      post :ready
    end
  end
  resources :emails, only: [:create] do
    collection do
      post :failure
    end
  end

  root :to => 'base#index'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_filter :require_user

  def show
  	@contacts = current_user.contacts.alphabetical
  	
  	@activities = Search.search(current_user.id, params).results
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.erb
<ul>
	<li><%= link_to 'Linked accounts', linked_accounts_path %></li>
	<li><%= link_to 'Update account', account_path %></li>
	<li><%= link_to 'Logout', logout_path %></li>
</ul>

<%= form_tag search_index_path, method: :get do %>
	<p>
		<%= label_tag :query, 'Search' %>
		<%= text_field_tag :query, params[:query] %>
	</p>

	<%= submit_tag 'Search' %>
<% end %>

<ul>
	<%= render @contacts %>
</ul>

<%= render partial: 'search/results', locals: { :activities => @activities } %>